### ISSUE TITLE
It must be a setuptools plugin

### ISSUE THREAD

**Issue by KOLANICH** [jwodder/read_version#1]

**Comment by jwodder** [comment]
Implementing this as a setuptools plugin would just mean the syntax changes from:

```
from read_version import read_version

setup(
    version = read_version('packagename', '__init__.py'),
    ...
)
```

to:

```
setup(
    read_version = ['packagename', '__init__.py'],
    ...
)
```

I don't see that as enough of an improvement to be worth mucking about with setuptools' underdocumented extension mechanisms.

(Note: [I actually submitted a pull request to setuptools](https://github.com/pypa/setuptools/pull/1753) that would expose this package's functionality via a `literal_attr:` directive in `setup.cfg` files, but it's been ignored so far.)

**Comment by jwodder** [comment]
I've changed my mind! — sort of.  As of the release yesterday of version 0.2.0, `read_version` can now be used a setuptools plugin, but rather than being configured through arguments to `setup()`, it reads its configuration from `pyproject.toml`, like so:

```
[tool.read_version]
# This sets your project's version to the value of the __version__ variable in packagename/__init__.py:
version = "packagename.__init__:__version__"
```

See [the README](https://github.com/jwodder/read_version/blob/master/README.rst) for more information.

**Comment by KOLANICH** [comment]
Nice, thanks.
